function get_x0(mindim, maxdim, plibs)
%GET_X0 Write x0 summaries for problems in the selected library.

if nargin < 3
    error('Usage: get_x0(mindim, maxdim, plibs)');
end

plibs = lower(char(plibs));
options.mindim = mindim;
options.maxdim = maxdim;
options.ptype = 'u';
if strcmpi(plibs, 'matcutest')
    exclude_list = {'ARGTRIGLS',...
    'BROWNAL',...
    'COATING',...
    'DIAMON2DLS',...
    'DIAMON3DLS',...
    'DMN15102LS', ...
    'DMN15103LS',...
    'DMN15332LS',...
    'DMN15333LS',...
    'DMN37142LS',...
    'DMN37143LS',...
    'ERRINRSM',...
    'HYDC20LS',...
    'LRA9A',...
    'LRCOVTYPE',...
    'LUKSAN12LS',...
    'LUKSAN14LS',...
    'LUKSAN17LS',...
    'LUKSAN21LS',...
    'LUKSAN22LS',...
    'MANCINO',...
    'PENALTY2',...
    'PENALTY3',...
    'VARDIM'};
else
    exclude_list = {'DIAMON2DLS',...
    'DIAMON2D',...
    'DIAMON3DLS',...
    'DIAMON3D',...
    'DMN15102LS',...
    'DMN15102',...
    'DMN15103LS',...
    'DMN15103',...
    'DMN15332LS',...
    'DMN15332',...
    'DMN15333LS',...
    'DMN15333',...
    'DMN37142LS',...
    'DMN37142',...
    'DMN37143LS',...
    'DMN37143',...
    'ROSSIMP3_mp',...
    'BAmL1SPLS',...
    'FBRAIN3LS',...
    'GAUSS1LS',...
    'GAUSS2LS',...
    'GAUSS3LS',...
    'HYDC20LS',...
    'HYDCAR6LS',...
    'LUKSAN11LS',...
    'LUKSAN12LS',...
    'LUKSAN13LS',...
    'LUKSAN14LS',...
    'LUKSAN17LS',...
    'LUKSAN21LS',...
    'LUKSAN22LS',...
    'METHANB8LS',...
    'METHANL8LS',...
    'SPINLS',...
    'VESUVIALS',...
    'VESUVIOLS',...
    'VESUVIOULS',...
    'YATP1CLS',... % The dimensions of the above problems are from 6 to 50. The following problems are from 51 to 200;
    'ARGLINA',...
    'ARGTRIGLS_100',...
    'EIGENALS_110',...
    'EIGENBLS_110',...
    'MANCINO_100',...
    'MODBEALE_200',...
    'MSQRTALS_100',...
    'MSQRTBLS_100',...
    'SENSORS_100',...
    'SPARSINE_100',...
    'SSBRYBND_100',...
    'TRIGON1_100',...
    'YATP1LS_120'};
end
switch plibs
    case 's2mpj'
        problem_list = s2mpj_select(options);
        load_problem = @(name) s2mpj_load(name);
    case 'matcutest'
        problem_list = matcutest_select(options);
        load_problem = @(name) matcutest_load(name);
    otherwise
        error('Unsupported plibs value: %s. Use ''s2mpj'' or ''matcutest''.', plibs);
end

if isstring(problem_list)
    problem_list = cellstr(problem_list);
elseif ischar(problem_list)
    problem_list = {problem_list};
end

if ~isempty(exclude_list)
    problem_list = problem_list(~ismember(problem_list, exclude_list));
end

num_problems = length(problem_list);
output_path = fullfile(fileparts(mfilename('fullpath')), ...
    sprintf('x0_summary_%d_%d_%s.txt', mindim, maxdim, plibs));

problems = cell(num_problems, 1);
x0_values = cell(num_problems, 1);
ratio_values = cell(num_problems, 1);
for i = 1:num_problems
    problem = problem_list{i};
    fprintf('Testing problem: %s\n', problem);
    p = load_problem(problem);
    x0 = p.x0;
    abs_x0 = abs(x0(:));
    max_abs = max(abs_x0);
    min_abs = min(abs_x0);
    if max_abs == 0 && min_abs == 0
        ratio = 1;
    elseif min_abs == 0
        ratio = Inf;
    else
        ratio = max_abs / min_abs;
    end
    problems{i} = problem;
    x0_values{i} = mat2str(x0(:).');
    ratio_values{i} = sprintf('%.16g', ratio);
end

problem_header = 'problem';
x0_header = 'x0';
ratio_header = 'abs_max_min_ratio';
problem_width = max(cellfun(@length, problems));
x0_width = max(cellfun(@length, x0_values));
ratio_width = max(cellfun(@length, ratio_values));
problem_width = max(problem_width, length(problem_header));
x0_width = max(x0_width, length(x0_header));
ratio_width = max(ratio_width, length(ratio_header));

fid = fopen(output_path, 'w');
if fid < 0
    error('Failed to open output file: %s', output_path);
end
fprintf(fid, '%-*s  %-*s  %-*s\n', problem_width, problem_header, x0_width, x0_header, ratio_width, ratio_header);
for i = 1:num_problems
    fprintf(fid, '%-*s  %-*s  %-*s\n', problem_width, problems{i}, x0_width, x0_values{i}, ratio_width, ratio_values{i});
end
fclose(fid);
fprintf('Wrote x0 summary to %s\n', output_path);

end