function verify_gradient_stop_no_extra_evaluations()
%VERIFY_GRADIENT_STOP_NO_EXTRA_EVALUATIONS checks gradient-stop accounting.

tests_dir = fileparts(mfilename('fullpath'));
addpath(fullfile(tests_dir, 'competitors'));
x0 = [1.1; 0.9; 1.2];
options = final_gradient_options(numel(x0));

[plain, plain_calls] = run_with_counter(false, false);
[diagnostic, diagnostic_calls] = run_with_counter(true, false);
[legacy, legacy_calls] = run_with_counter(false, true);
[defaults, default_calls] = run_with_defaults();

assert(strcmp(plain.output.message, 'The estimated gradient is small.'), ...
    'The focused case did not activate the estimated-gradient stop.');
assert(isequaln(plain.x, diagnostic.x) ...
    && isequaln(plain.f, diagnostic.f) ...
    && plain.exitflag == diagnostic.exitflag ...
    && isequaln(plain.output.fhist, diagnostic.output.fhist), ...
    'Diagnostic tracing changed the solver trajectory.');
assert(isequaln(plain_calls, diagnostic_calls), ...
    'Diagnostic tracing changed the objective-call sequence.');
assert(isequaln(plain.x, legacy.x) ...
    && isequaln(plain.f, legacy.f) ...
    && plain.exitflag == legacy.exitflag ...
    && isequaln(plain.output.fhist, legacy.output.fhist) ...
    && isequaln(plain_calls, legacy_calls), ...
    'The direct rho option and its legacy scale encoding are not equivalent.');
assert(isequaln(plain.x, defaults.x) ...
    && isequaln(plain.f, defaults.f) ...
    && plain.exitflag == defaults.exitflag ...
    && isequaln(plain.output.fhist, defaults.output.fhist) ...
    && isequaln(plain_calls, default_calls), ...
    'The tuned gradient-stop defaults differ from the explicit final options.');
assert_objective_accounting(plain, plain_calls);
assert_objective_accounting(diagnostic, diagnostic_calls);
assert_objective_accounting(legacy, legacy_calls);
assert_objective_accounting(defaults, default_calls);
assert(~isempty(diagnostic.output.gradient_stop_diagnostics) ...
    && diagnostic.output.gradient_stop_diagnostics(end).stop_decision, ...
    'The diagnostic trace did not record the gradient stop.');

fprintf('GRADIENT_STOP_NO_EXTRA_EVALUATIONS_OK\n');

    function [result, calls] = run_with_counter( ...
            enable_diagnostics, use_legacy_scale)
        calls = zeros(numel(x0), 0);
        run_options = options;
        run_options.output_gradient_stop_diagnostics = enable_diagnostics;
        if use_legacy_scale
            run_options = rmfield(run_options, 'grad_reference_relative_tol');
            run_options.grad_reference_scale_factor = 10000;
        end
        [result.x, result.f, result.exitflag, result.output] = ...
            accelerated_bds_options(@counted_objective, x0, run_options);

        function value = counted_objective(x)
            calls(:, end + 1) = x(:);
            value = sum((x(:) - 1).^2);
        end
    end

    function [result, calls] = run_with_defaults()
        calls = zeros(numel(x0), 0);
        run_options = rmfield(options, { ...
            'use_gradient_reference_reliability', ...
            'grad_reference_consistency_tol', ...
            'grad_reference_relative_tol'});
        [result.x, result.f, result.exitflag, result.output] = ...
            accelerated_bds_options(@counted_objective, x0, run_options);

        function value = counted_objective(x)
            calls(:, end + 1) = x(:);
            value = sum((x(:) - 1).^2);
        end
    end

end

function options = final_gradient_options(n)

options = struct('Algorithm', 'cbds', ...
    'MaxFunctionEvaluations', 500 * n, 'StepTolerance', 1e-6, ...
    'alpha_init', ones(n, 1), 'seed', 0, ...
    'use_productive_direction_memory', true, ...
    'use_sweep_pattern_direction', true, ...
    'use_momentum_extrapolation', true, ...
    'use_function_value_stop', false, ...
    'use_estimated_gradient_stop', true, ...
    'grad_window_size', 1, 'grad_tol', 1e-6, ...
    'lipschitz_constant', 1e3, ...
    'use_gradient_reference_reliability', true, ...
    'grad_reference_consistency_tol', 0.1, ...
    'grad_reference_relative_tol', 1e-2, ...
    'output_xhist', true);

end

function assert_objective_accounting(result, calls)

assert(result.output.funcCount == size(calls, 2), ...
    'output.funcCount does not match the actual objective-call count.');
assert(isequaln(result.output.xhist, calls), ...
    'Some objective calls are missing from the ordinary evaluation history.');
assert(numel(result.output.fhist) == size(calls, 2), ...
    'Function-value history and actual objective-call count differ.');

end
