function manifest = run_gradient_no_stop_trace_collection()
%RUN_GRADIENT_NO_STOP_TRACE_COLLECTION records native poll gradient traces.

repo_dir = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
tests_dir = fullfile(repo_dir, 'tests');
cd(repo_dir);
setup;
addpath(tests_dir);
addpath(fullfile(tests_dir, 'competitors'));
optiprofiler_root = fullfile(getenv('HOME'), 'local', 'optiprofiler', ...
    'matlab', 'optiprofiler');
addpath(fullfile(optiprofiler_root, 'src'));
addpath(fullfile(optiprofiler_root, 'problem_libs'));
addpath(fullfile(optiprofiler_root, 'problem_libs', 's2mpj'));

problem_names = frozen_problem_names();
features = {'plain', 'linearly_transformed'};
real_seed = 211;
timestamp = char(datetime('now', 'Format', 'yyyyMMdd_HHmmss'));
run_root = fullfile(tests_dir, 'testdata', ...
    ['gradient_no_stop_traces_', timestamp]);
mkdir(run_root);
manifest = struct('status', 'RUNNING', ...
    'started_at', char(datetime('now')), 'run_root', run_root, ...
    'problem_names', {problem_names}, 'features', {features}, ...
    'real_seed', real_seed, 'max_eval_factor', 500, ...
    'uses_extra_function_evaluations', false);
save(fullfile(run_root, 'manifest.mat'), 'manifest');

for i_feature = 1:numel(features)
    feature_name = features{i_feature};
    feature = Feature(feature_name);
    runs = cell(numel(problem_names), 1);
    for i_problem = 1:numel(problem_names)
        problem = s2mpj_load(problem_names{i_problem});
        featured_problem = FeaturedProblem( ...
            problem, feature, 500 * problem.n, real_seed);
        options = solver_options(featured_problem.x0);
        [xopt, fopt, exitflag, output] = accelerated_bds_options( ...
            @(x) featured_problem.fun(x), featured_problem.x0, options);
        run = struct('problem_name', problem_names{i_problem}, ...
            'dimension', problem.n, 'feature_name', feature_name, ...
            'x0', featured_problem.x0, 'xopt', xopt, 'fopt', fopt, ...
            'exitflag', exitflag, 'func_count', output.funcCount, ...
            'trace', output.gradient_stop_diagnostics);
        runs{i_problem} = run;
        fprintf(['GRADIENT_TRACE=FEATURE:%s,INDEX:%d,PROBLEM:%s,', ...
            'NF:%d,TRACE:%d,FOPT:%.17g\n'], feature_name, i_problem, ...
            problem_names{i_problem}, output.funcCount, numel(run.trace), fopt);
    end
    save(fullfile(run_root, [feature_name, '_traces.mat']), ...
        'runs', 'feature_name', 'problem_names', 'real_seed', '-v7.3');
    fprintf('GRADIENT_TRACE_FEATURE_OK=%s\n', feature_name);
end

manifest.status = 'COMPLETE';
manifest.finished_at = char(datetime('now'));
save(fullfile(run_root, 'manifest.mat'), 'manifest');
fprintf('GRADIENT_NO_STOP_TRACE_RUN_ROOT=%s\n', run_root);
fprintf('GRADIENT_NO_STOP_TRACE_COLLECTION_OK\n');

end

function options = solver_options(x0)

options = struct('Algorithm', 'cbds', ...
    'MaxFunctionEvaluations', 500 * numel(x0), 'StepTolerance', 1e-6, ...
    'ftarget', -Inf, 'expand', 1.8, 'shrink', 0.5, ...
    'is_noisy', false, 'forcing_function', @(alpha) alpha^2, ...
    'reduction_factor', [0, eps, eps], ...
    'polling_inner', 'opportunistic', 'cycling_inner', 1, 'seed', 0, ...
    'use_productive_direction_memory', true, ...
    'use_iteration_pattern_step', true, ...
    'use_momentum_extrapolation', true, ...
    'use_function_value_stop', false, ...
    'use_estimated_gradient_stop', false, ...
    'output_gradient_stop_diagnostics', true);
options.alpha_init = max(abs(x0(:)), options.StepTolerance);
options.alpha_init(x0(:) == 0) = 1;

end

function names = frozen_problem_names()

selection = struct();
selection.ptype = 'u';
selection.mindim = 6;
selection.maxdim = 50;
selection.excludelist = { ...
    'DIAMON2DLS', 'DIAMON2D', 'DIAMON3DLS', 'DIAMON3D', ...
    'DMN15102LS', 'DMN15102', 'DMN15103LS', 'DMN15103', ...
    'DMN15332LS', 'DMN15332', 'DMN15333LS', 'DMN15333', ...
    'DMN37142LS', 'DMN37142', 'DMN37143LS', 'DMN37143', ...
    'ROSSIMP3_mp', 'BAmL1SPLS', 'FBRAIN3LS', 'GAUSS1LS', ...
    'GAUSS2LS', 'GAUSS3LS', 'HYDC20LS', 'HYDCAR6LS', ...
    'LUKSAN11LS', 'LUKSAN12LS', 'LUKSAN13LS', ...
    'LUKSAN14LS', 'LUKSAN17LS', 'LUKSAN21LS', 'LUKSAN22LS', ...
    'METHANB8LS', 'METHANL8LS', 'SPINLS', 'VESUVIALS', ...
    'VESUVIOLS', 'VESUVIOULS', 'YATP1CLS'};
names = s2mpj_select(selection);
assert(numel(names) == 122, 'Expected the frozen 122-problem set.');

end
