name: Stress test

on:
  # Run this expensive stress test monthly rather than on every push.
  schedule:
    - cron: '0 18 1 * *'
  # Trigger the workflow manually.
  workflow_dispatch:
    inputs:
      dimension:
        description: Dimension (Optional)
        required: false
      max-function-evaluations:
        description: Maximum Function Evaluations (Optional)
        required: false

jobs:
  test:
    name: Stress test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        matlab: [R2024b, latest]
        with_optim_toolbox: [no]
        solver: [cbds, pbds, rbds, pads, ds]
        tough: [true, false]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache MATLAB
        id: cache-matlab
        uses: actions/cache@v4
        with:
          path: ${{ runner.tool_cache }}/MATLAB
          key: ${{ matrix.os }}-${{ matrix.matlab }}-${{ matrix.with_optim_toolbox }}

      - name: Set up MATLAB 
        uses: matlab-actions/setup-matlab@v2.1.2
        with:
          release: ${{ matrix.matlab }}

      - name: Run test
        uses: matlab-actions/run-command@v2.1.1
        with:
          command: |
            root_dir = pwd()

            % Conduct your tests
            path_tests = fullfile(root_dir, 'tests');
            cd(path_tests);

            % Run tests
            options.Algorithm = "${{ matrix.solver }}";
            options.tough = ${{ matrix.tough }};
            if ~isempty('${{ inputs.dimension }}')
                options.n = str2double('${{ inputs.dimension }}');
            end
            if ~isempty('${{ inputs.max-function-evaluations }}')
                options.MaxFunctionEvaluations = ...
                    str2double('${{ inputs.max-function-evaluations }}');
            end
            stress("bds", options);
